service: lambda-xray

frameworkVersion: ">=1.22.0 <2.0.0"


plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing

# custom:
#   pythonRequirements:
#     dockerizePip: true

custom:
  bucketName: ${self:service}-${opt:stage, 'dev'}

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  profile: myaws
  tracing: true # enable tracing 
  environment:
    S3_BUCKET: ${self:custom.bucketName}

  iamRoleStatements:
  - Effect: Allow
    Action:
      - xray:PutTelemetryRecords
      - xray:PutTraceSegments
    Resource: "*"
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:GetObject
    Resource:
      - arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*

#  environment:
#    variable1: value1

package:
  exclude:
    - README.md
    - .gitignore
    - requirements.txt
    - tests/**
    - serverless.*
    - node_modules/**
    - package.json
    - package-lock.json

functions:
  hello:
    handler: handler.hello

    events:
      - http:
          path: /hello
          method: get

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}