service: lambda-xray

frameworkVersion: ">=1.22.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  profile: myaws
#  stage: dev

#  environment:
#    variable1: value1

#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello

    events:
      - http:
          path: /hello
          method: get

#resources:
#  Resources:
